name: "P6 GHA: Builds a p6df- plugin"
description: "P6 GHA: Builds a p6df- plugin"
author: "Philip M. Gollucci"

inputs:
  gh_token:
    description: "GitHub Token"
    required: true
  shellcheck:
    description: "Run shellcheck (true/false)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0

    - name: Generic Build Steps
      uses: p6m7g8-actions/p6-build@main
      with:
        gh_token: ${{ inputs.gh_token }}
        shellcheck: ${{ inputs.shellcheck }}

    - name: Install zsh & time
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y zsh time

    - name: Checkout p6common
      uses: actions/checkout@v5.0.0
      with:
        repository: p6m7g8-dotfiles/p6common
        path: p6common

    - name: Dependant Repositories
      shell: bash
      run: |
        set +e
        set -x
        env | sort
        mod=$(echo "$GITHUB_REPOSITORY" | awk -F/ '{n=$2; sub(/^p6df-/, "", n); print n}')
        zsh -c ". ./p6common/init.zsh; p6df::modules::p6common::gha::ModuleDeps $mod"
        set +x

    - name: Test
      shell: bash
      env:
        P6_DFZ_SRC_P6M7G8_DOTFILES_DIR: .
        TERM: xterm
      run: zsh -e p6common/bin/p6ctl test
