name: "P6 GHA: Builds a p6df- plugin"
description: "P6 GHA: Builds a p6df- plugin"
author: "Philip M. Gollucci"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install zsh
      shell: bash
      run: sudo apt-get update; sudo apt-get install time zsh -y
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        repository: p6m7g8-dotfiles/p6common
        path: p6common
    - name: Dependant Repositories
      shell: bash
      run: |
        mod=$(echo "$GITHUB_REPOSITORY" | awk -F/ '{print $2}' | awk -F'-' '{print $2}')
        set +e
        set -x
        zsh -c ". ./p6common/init.zsh; p6df::modules::p6common::gha::ModuleDeps $mod"
        set +x
    - name: Test
      shell: bash
      env:
        P6_DFZ_SRC_P6M7G8_DOTFILES_DIR: .
        TERM: xterm
      run: zsh -e p6common/bin/p6ctl test
